include:
  - board: xiao_ble/nrf52840/zmk
    shield: adept_board
    # snippet: zmk-usb-logging
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
